// <auto-generated />
namespace Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddReferenceData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReferenceData));
        
        string IMigrationMetadata.Id
        {
            get { return "201211301653366_AddReferenceData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
