// <auto-generated />
namespace Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UsertableFieldLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsertableFieldLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201211211853413_UsertableFieldLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
